---
abstract: 'M::B utility methods'
author:
  - unknown
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Usul-Build
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Class::Usul::Build:
    file: lib/Class/Usul/Build.pm
    version: v0.20.3
  Class::Usul::Build::InstallActions:
    file: lib/Class/Usul/Build/InstallActions.pm
    version: v0.20.2
  Class::Usul::Build::Plugin::Debian:
    file: lib/Class/Usul/Build/Plugin/Debian.pm
    version: v0.20.2
  Class::Usul::Build::Questions:
    file: lib/Class/Usul/Build/Questions.pm
    version: v0.20.3
  Class::Usul::Build::VCS:
    file: lib/Class/Usul/Build/VCS.pm
    version: v0.20.1
recommends:
  App::cpanminus: 1.6005
  DhMakePerl: 0.72
requires:
  Class::Usul: v0.20.0
  Email::Date::Format: 1.002
  Git::Class: 0.12
  MRO::Compat: 0.11
  Module::Metadata: 1.000011
  Perl::Version: 1.011
  SVN::Class: 0.16
  Software::License: 0.102341
  Text::Format: 0.53
  Try::Tiny: 0.09
  local::lib: 1.008004
  parent: 0.224
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Usul-Build
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.20.3
