---
abstract: 'Module::Build methods for standalone applications'
author:
  - unknown
build_requires:
  Module::Build: 0.4004
  version: 0.88
configure_requires:
  Module::Build: 0.4004
  version: 0.88
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Usul-Build
no_index:
  directory:
    - examples
    - inc
    - share
    - t
provides:
  Class::Usul::Build:
    file: lib/Class/Usul/Build.pm
    version: v0.22.3
  Class::Usul::Build::InstallActions:
    file: lib/Class/Usul/Build/InstallActions.pm
    version: v0.22.2
  Class::Usul::Build::Questions:
    file: lib/Class/Usul/Build/Questions.pm
    version: v0.22.2
recommends:
  App::cpanminus: 1.6005
requires:
  Class::Usul: v0.23.0
  MRO::Compat: 0.11
  Module::Metadata: 1.000011
  Moo: 1.003
  Perl::Version: 1.011
  Try::Tiny: 0.09
  local::lib: 1.008004
  namespace::sweep: 0.006
  parent: 0.224
  perl: 5.01
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Usul-Build
  homepage: http://www.roxsoft.co.uk
  license: http://dev.perl.org/licenses/
version: v0.22.3
